// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

type ConfigSource string

const (
	ConfigSourceGlobal  ConfigSource = "GLOBAL"
	ConfigSourceEnv     ConfigSource = "ENV"
	ConfigSourceHelm    ConfigSource = "HELM"
	ConfigSourceUnknown ConfigSource = "UNKNOWN"
)

var AllConfigSource = []ConfigSource{
	ConfigSourceGlobal,
	ConfigSourceEnv,
	ConfigSourceHelm,
	ConfigSourceUnknown,
}

type ConfigType string

const (
	ConfigTypeString      ConfigType = "STRING"
	ConfigTypeInt         ConfigType = "INT"
	ConfigTypeBool        ConfigType = "BOOL"
	ConfigTypeStringArray ConfigType = "STRING_ARRAY"
)

var AllConfigType = []ConfigType{
	ConfigTypeString,
	ConfigTypeInt,
	ConfigTypeBool,
	ConfigTypeStringArray,
}

// CreateConfigurationMutationConfigurationCreateConfiguration includes the requested fields of the GraphQL type Configuration.
type CreateConfigurationMutationConfigurationCreateConfiguration struct {
	Id      string                                                            `json:"id"`
	Value   *CreateConfigurationMutationConfigurationCreateConfigurationValue `json:"value"`
	Content *json.RawMessage                                                  `json:"content"`
	Source  ConfigSource                                                      `json:"source"`
}

// GetId returns CreateConfigurationMutationConfigurationCreateConfiguration.Id, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfiguration) GetId() string { return v.Id }

// GetValue returns CreateConfigurationMutationConfigurationCreateConfiguration.Value, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfiguration) GetValue() *CreateConfigurationMutationConfigurationCreateConfigurationValue {
	return v.Value
}

// GetContent returns CreateConfigurationMutationConfigurationCreateConfiguration.Content, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfiguration) GetContent() *json.RawMessage {
	return v.Content
}

// GetSource returns CreateConfigurationMutationConfigurationCreateConfiguration.Source, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfiguration) GetSource() ConfigSource {
	return v.Source
}

// CreateConfigurationMutationConfigurationCreateConfigurationValue includes the requested fields of the GraphQL type Value.
type CreateConfigurationMutationConfigurationCreateConfigurationValue struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
}

// GetKey returns CreateConfigurationMutationConfigurationCreateConfigurationValue.Key, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfigurationValue) GetKey() string {
	return v.Key
}

// GetDisplayName returns CreateConfigurationMutationConfigurationCreateConfigurationValue.DisplayName, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationConfigurationCreateConfigurationValue) GetDisplayName() string {
	return v.DisplayName
}

// CreateConfigurationMutationResponse is returned by CreateConfigurationMutation on success.
type CreateConfigurationMutationResponse struct {
	ConfigurationCreate *CreateConfigurationMutationConfigurationCreateConfiguration `json:"configurationCreate"`
}

// GetConfigurationCreate returns CreateConfigurationMutationResponse.ConfigurationCreate, and is useful for accessing the field via an interface.
func (v *CreateConfigurationMutationResponse) GetConfigurationCreate() *CreateConfigurationMutationConfigurationCreateConfiguration {
	return v.ConfigurationCreate
}

type DeploymentStatusState string

const (
	DeploymentStatusStateUnknown  DeploymentStatusState = "UNKNOWN"
	DeploymentStatusStateCreated  DeploymentStatusState = "CREATED"
	DeploymentStatusStatePending  DeploymentStatusState = "PENDING"
	DeploymentStatusStateDeployed DeploymentStatusState = "DEPLOYED"
	DeploymentStatusStateFailed   DeploymentStatusState = "FAILED"
	DeploymentStatusStateDisabled DeploymentStatusState = "DISABLED"
)

var AllDeploymentStatusState = []DeploymentStatusState{
	DeploymentStatusStateUnknown,
	DeploymentStatusStateCreated,
	DeploymentStatusStatePending,
	DeploymentStatusStateDeployed,
	DeploymentStatusStateFailed,
	DeploymentStatusStateDisabled,
}

type EnvironmentKind string

const (
	EnvironmentKindTenant     EnvironmentKind = "TENANT"
	EnvironmentKindManagement EnvironmentKind = "MANAGEMENT"
	EnvironmentKindOnprem     EnvironmentKind = "ONPREM"
	EnvironmentKindLegacy     EnvironmentKind = "LEGACY"
)

var AllEnvironmentKind = []EnvironmentKind{
	EnvironmentKindTenant,
	EnvironmentKindManagement,
	EnvironmentKindOnprem,
	EnvironmentKindLegacy,
}

// GetDeploymentDetailDeployment includes the requested fields of the GraphQL type Deployment.
type GetDeploymentDetailDeployment struct {
	Id          string                                                   `json:"id"`
	Feature     *GetDeploymentDetailDeploymentFeature                    `json:"feature"`
	Target      []*GetDeploymentDetailDeploymentTargetEnvironmentLabel   `json:"target"`
	Created     string                                                   `json:"created"`
	Ci          bool                                                     `json:"ci"`
	Description *string                                                  `json:"description"`
	Statuses    []*GetDeploymentDetailDeploymentStatusesDeploymentStatus `json:"statuses"`
}

// GetId returns GetDeploymentDetailDeployment.Id, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetId() string { return v.Id }

// GetFeature returns GetDeploymentDetailDeployment.Feature, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetFeature() *GetDeploymentDetailDeploymentFeature {
	return v.Feature
}

// GetTarget returns GetDeploymentDetailDeployment.Target, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetTarget() []*GetDeploymentDetailDeploymentTargetEnvironmentLabel {
	return v.Target
}

// GetCreated returns GetDeploymentDetailDeployment.Created, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetCreated() string { return v.Created }

// GetCi returns GetDeploymentDetailDeployment.Ci, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetCi() bool { return v.Ci }

// GetDescription returns GetDeploymentDetailDeployment.Description, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetDescription() *string { return v.Description }

// GetStatuses returns GetDeploymentDetailDeployment.Statuses, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeployment) GetStatuses() []*GetDeploymentDetailDeploymentStatusesDeploymentStatus {
	return v.Statuses
}

// GetDeploymentDetailDeploymentFeature includes the requested fields of the GraphQL type Feature.
type GetDeploymentDetailDeploymentFeature struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// GetName returns GetDeploymentDetailDeploymentFeature.Name, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentFeature) GetName() string { return v.Name }

// GetVersion returns GetDeploymentDetailDeploymentFeature.Version, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentFeature) GetVersion() string { return v.Version }

// GetDeploymentDetailDeploymentStatusesDeploymentStatus includes the requested fields of the GraphQL type DeploymentStatus.
type GetDeploymentDetailDeploymentStatusesDeploymentStatus struct {
	State        DeploymentStatusState                                             `json:"state"`
	Message      string                                                            `json:"message"`
	LastModified string                                                            `json:"lastModified"`
	Environment  *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment `json:"environment"`
}

// GetState returns GetDeploymentDetailDeploymentStatusesDeploymentStatus.State, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatus) GetState() DeploymentStatusState {
	return v.State
}

// GetMessage returns GetDeploymentDetailDeploymentStatusesDeploymentStatus.Message, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatus) GetMessage() string { return v.Message }

// GetLastModified returns GetDeploymentDetailDeploymentStatusesDeploymentStatus.LastModified, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatus) GetLastModified() string {
	return v.LastModified
}

// GetEnvironment returns GetDeploymentDetailDeploymentStatusesDeploymentStatus.Environment, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatus) GetEnvironment() *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment {
	return v.Environment
}

// GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment includes the requested fields of the GraphQL type Environment.
type GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment struct {
	Name   string                                                                  `json:"name"`
	Tenant *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant `json:"tenant"`
}

// GetName returns GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment.Name, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment) GetName() string {
	return v.Name
}

// GetTenant returns GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment.Tenant, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironment) GetTenant() *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant {
	return v.Tenant
}

// GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant includes the requested fields of the GraphQL type Tenant.
type GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant struct {
	Name string `json:"name"`
}

// GetName returns GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant.Name, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentStatusesDeploymentStatusEnvironmentTenant) GetName() string {
	return v.Name
}

// GetDeploymentDetailDeploymentTargetEnvironmentLabel includes the requested fields of the GraphQL type EnvironmentLabel.
type GetDeploymentDetailDeploymentTargetEnvironmentLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns GetDeploymentDetailDeploymentTargetEnvironmentLabel.Key, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentTargetEnvironmentLabel) GetKey() string { return v.Key }

// GetValue returns GetDeploymentDetailDeploymentTargetEnvironmentLabel.Value, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailDeploymentTargetEnvironmentLabel) GetValue() string { return v.Value }

// GetDeploymentDetailResponse is returned by GetDeploymentDetail on success.
type GetDeploymentDetailResponse struct {
	Deployment *GetDeploymentDetailDeployment `json:"deployment"`
}

// GetDeployment returns GetDeploymentDetailResponse.Deployment, and is useful for accessing the field via an interface.
func (v *GetDeploymentDetailResponse) GetDeployment() *GetDeploymentDetailDeployment {
	return v.Deployment
}

// GetDeploymentsDeploymentsDeployment includes the requested fields of the GraphQL type Deployment.
type GetDeploymentsDeploymentsDeployment struct {
	Id       string                                                         `json:"id"`
	Feature  *GetDeploymentsDeploymentsDeploymentFeature                    `json:"feature"`
	Target   []*GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel   `json:"target"`
	Created  string                                                         `json:"created"`
	Ci       bool                                                           `json:"ci"`
	Statuses []*GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus `json:"statuses"`
}

// GetId returns GetDeploymentsDeploymentsDeployment.Id, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetId() string { return v.Id }

// GetFeature returns GetDeploymentsDeploymentsDeployment.Feature, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetFeature() *GetDeploymentsDeploymentsDeploymentFeature {
	return v.Feature
}

// GetTarget returns GetDeploymentsDeploymentsDeployment.Target, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetTarget() []*GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel {
	return v.Target
}

// GetCreated returns GetDeploymentsDeploymentsDeployment.Created, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetCreated() string { return v.Created }

// GetCi returns GetDeploymentsDeploymentsDeployment.Ci, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetCi() bool { return v.Ci }

// GetStatuses returns GetDeploymentsDeploymentsDeployment.Statuses, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeployment) GetStatuses() []*GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus {
	return v.Statuses
}

// GetDeploymentsDeploymentsDeploymentFeature includes the requested fields of the GraphQL type Feature.
type GetDeploymentsDeploymentsDeploymentFeature struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// GetName returns GetDeploymentsDeploymentsDeploymentFeature.Name, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeploymentFeature) GetName() string { return v.Name }

// GetVersion returns GetDeploymentsDeploymentsDeploymentFeature.Version, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeploymentFeature) GetVersion() string { return v.Version }

// GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus includes the requested fields of the GraphQL type DeploymentStatus.
type GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus struct {
	State DeploymentStatusState `json:"state"`
}

// GetState returns GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus.State, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeploymentStatusesDeploymentStatus) GetState() DeploymentStatusState {
	return v.State
}

// GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel includes the requested fields of the GraphQL type EnvironmentLabel.
type GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel.Key, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel) GetKey() string { return v.Key }

// GetValue returns GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel.Value, and is useful for accessing the field via an interface.
func (v *GetDeploymentsDeploymentsDeploymentTargetEnvironmentLabel) GetValue() string { return v.Value }

// GetDeploymentsListDeploymentsDeployment includes the requested fields of the GraphQL type Deployment.
type GetDeploymentsListDeploymentsDeployment struct {
	Id       string                                                             `json:"id"`
	Feature  *GetDeploymentsListDeploymentsDeploymentFeature                    `json:"feature"`
	Target   []*GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel   `json:"target"`
	Created  string                                                             `json:"created"`
	Ci       bool                                                               `json:"ci"`
	Statuses []*GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus `json:"statuses"`
}

// GetId returns GetDeploymentsListDeploymentsDeployment.Id, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetId() string { return v.Id }

// GetFeature returns GetDeploymentsListDeploymentsDeployment.Feature, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetFeature() *GetDeploymentsListDeploymentsDeploymentFeature {
	return v.Feature
}

// GetTarget returns GetDeploymentsListDeploymentsDeployment.Target, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetTarget() []*GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel {
	return v.Target
}

// GetCreated returns GetDeploymentsListDeploymentsDeployment.Created, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetCreated() string { return v.Created }

// GetCi returns GetDeploymentsListDeploymentsDeployment.Ci, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetCi() bool { return v.Ci }

// GetStatuses returns GetDeploymentsListDeploymentsDeployment.Statuses, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeployment) GetStatuses() []*GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus {
	return v.Statuses
}

// GetDeploymentsListDeploymentsDeploymentFeature includes the requested fields of the GraphQL type Feature.
type GetDeploymentsListDeploymentsDeploymentFeature struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// GetName returns GetDeploymentsListDeploymentsDeploymentFeature.Name, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeploymentFeature) GetName() string { return v.Name }

// GetVersion returns GetDeploymentsListDeploymentsDeploymentFeature.Version, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeploymentFeature) GetVersion() string { return v.Version }

// GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus includes the requested fields of the GraphQL type DeploymentStatus.
type GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus struct {
	State DeploymentStatusState `json:"state"`
}

// GetState returns GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus.State, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeploymentStatusesDeploymentStatus) GetState() DeploymentStatusState {
	return v.State
}

// GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel includes the requested fields of the GraphQL type EnvironmentLabel.
type GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel.Key, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel) GetKey() string { return v.Key }

// GetValue returns GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel.Value, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListDeploymentsDeploymentTargetEnvironmentLabel) GetValue() string {
	return v.Value
}

// GetDeploymentsListResponse is returned by GetDeploymentsList on success.
type GetDeploymentsListResponse struct {
	Deployments []*GetDeploymentsListDeploymentsDeployment `json:"deployments"`
}

// GetDeployments returns GetDeploymentsListResponse.Deployments, and is useful for accessing the field via an interface.
func (v *GetDeploymentsListResponse) GetDeployments() []*GetDeploymentsListDeploymentsDeployment {
	return v.Deployments
}

// GetDeploymentsResponse is returned by GetDeployments on success.
type GetDeploymentsResponse struct {
	Deployments []*GetDeploymentsDeploymentsDeployment `json:"deployments"`
}

// GetDeployments returns GetDeploymentsResponse.Deployments, and is useful for accessing the field via an interface.
func (v *GetDeploymentsResponse) GetDeployments() []*GetDeploymentsDeploymentsDeployment {
	return v.Deployments
}

// GetFeatureConfigConfigurationConfigurations includes the requested fields of the GraphQL type Configurations.
// The GraphQL type's documentation follows.
//
// Configurations contains configuration and computed values for one feature
type GetFeatureConfigConfigurationConfigurations struct {
	Configuration []*GetFeatureConfigConfigurationConfigurationsConfiguration `json:"configuration"`
}

// GetConfiguration returns GetFeatureConfigConfigurationConfigurations.Configuration, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurations) GetConfiguration() []*GetFeatureConfigConfigurationConfigurationsConfiguration {
	return v.Configuration
}

// GetFeatureConfigConfigurationConfigurationsConfiguration includes the requested fields of the GraphQL type Configuration.
type GetFeatureConfigConfigurationConfigurationsConfiguration struct {
	Id      string                                                         `json:"id"`
	Value   *GetFeatureConfigConfigurationConfigurationsConfigurationValue `json:"value"`
	Content *json.RawMessage                                               `json:"content"`
	Source  ConfigSource                                                   `json:"source"`
}

// GetId returns GetFeatureConfigConfigurationConfigurationsConfiguration.Id, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfiguration) GetId() string { return v.Id }

// GetValue returns GetFeatureConfigConfigurationConfigurationsConfiguration.Value, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfiguration) GetValue() *GetFeatureConfigConfigurationConfigurationsConfigurationValue {
	return v.Value
}

// GetContent returns GetFeatureConfigConfigurationConfigurationsConfiguration.Content, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfiguration) GetContent() *json.RawMessage {
	return v.Content
}

// GetSource returns GetFeatureConfigConfigurationConfigurationsConfiguration.Source, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfiguration) GetSource() ConfigSource {
	return v.Source
}

// GetFeatureConfigConfigurationConfigurationsConfigurationValue includes the requested fields of the GraphQL type Value.
type GetFeatureConfigConfigurationConfigurationsConfigurationValue struct {
	Key         string                                                                 `json:"key"`
	DisplayName string                                                                 `json:"displayName"`
	Description string                                                                 `json:"description"`
	Required    bool                                                                   `json:"required"`
	Config      *GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig   `json:"config"`
	Computed    *GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed `json:"computed"`
}

// GetKey returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.Key, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetKey() string { return v.Key }

// GetDisplayName returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.DisplayName, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetDisplayName() string {
	return v.DisplayName
}

// GetDescription returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.Description, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetDescription() string {
	return v.Description
}

// GetRequired returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.Required, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetRequired() bool {
	return v.Required
}

// GetConfig returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.Config, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetConfig() *GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig {
	return v.Config
}

// GetComputed returns GetFeatureConfigConfigurationConfigurationsConfigurationValue.Computed, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValue) GetComputed() *GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed {
	return v.Computed
}

// GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed includes the requested fields of the GraphQL type Computed.
type GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed struct {
	Template string `json:"template"`
}

// GetTemplate returns GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed.Template, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValueComputed) GetTemplate() string {
	return v.Template
}

// GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig includes the requested fields of the GraphQL type Config.
type GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig struct {
	Type   ConfigType `json:"type"`
	Secret bool       `json:"secret"`
}

// GetType returns GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig.Type, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig) GetType() ConfigType {
	return v.Type
}

// GetSecret returns GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig.Secret, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigConfigurationConfigurationsConfigurationValueConfig) GetSecret() bool {
	return v.Secret
}

// GetFeatureConfigResponse is returned by GetFeatureConfig on success.
type GetFeatureConfigResponse struct {
	Configuration *GetFeatureConfigConfigurationConfigurations `json:"configuration"`
}

// GetConfiguration returns GetFeatureConfigResponse.Configuration, and is useful for accessing the field via an interface.
func (v *GetFeatureConfigResponse) GetConfiguration() *GetFeatureConfigConfigurationConfigurations {
	return v.Configuration
}

// GetFeatureLogResponse is returned by GetFeatureLog on success.
type GetFeatureLogResponse struct {
	// tenant returns the given tenant.
	Tenant *GetFeatureLogTenant `json:"tenant"`
}

// GetTenant returns GetFeatureLogResponse.Tenant, and is useful for accessing the field via an interface.
func (v *GetFeatureLogResponse) GetTenant() *GetFeatureLogTenant { return v.Tenant }

// GetFeatureLogTenant includes the requested fields of the GraphQL type Tenant.
type GetFeatureLogTenant struct {
	Environment *GetFeatureLogTenantEnvironment `json:"environment"`
}

// GetEnvironment returns GetFeatureLogTenant.Environment, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenant) GetEnvironment() *GetFeatureLogTenantEnvironment { return v.Environment }

// GetFeatureLogTenantEnvironment includes the requested fields of the GraphQL type Environment.
type GetFeatureLogTenantEnvironment struct {
	Feature *GetFeatureLogTenantEnvironmentFeature `json:"feature"`
}

// GetFeature returns GetFeatureLogTenantEnvironment.Feature, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironment) GetFeature() *GetFeatureLogTenantEnvironmentFeature {
	return v.Feature
}

// GetFeatureLogTenantEnvironmentFeature includes the requested fields of the GraphQL type Feature.
type GetFeatureLogTenantEnvironmentFeature struct {
	Name          string                                              `json:"name"`
	Status        *GetFeatureLogTenantEnvironmentFeatureStatus        `json:"status"`
	HelmValueDiff *GetFeatureLogTenantEnvironmentFeatureHelmValueDiff `json:"helmValueDiff"`
}

// GetName returns GetFeatureLogTenantEnvironmentFeature.Name, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeature) GetName() string { return v.Name }

// GetStatus returns GetFeatureLogTenantEnvironmentFeature.Status, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeature) GetStatus() *GetFeatureLogTenantEnvironmentFeatureStatus {
	return v.Status
}

// GetHelmValueDiff returns GetFeatureLogTenantEnvironmentFeature.HelmValueDiff, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeature) GetHelmValueDiff() *GetFeatureLogTenantEnvironmentFeatureHelmValueDiff {
	return v.HelmValueDiff
}

// GetFeatureLogTenantEnvironmentFeatureHelmValueDiff includes the requested fields of the GraphQL type HelmValueDiff.
type GetFeatureLogTenantEnvironmentFeatureHelmValueDiff struct {
	Difference HelmValueDifference `json:"difference"`
	Diff       string              `json:"diff"`
}

// GetDifference returns GetFeatureLogTenantEnvironmentFeatureHelmValueDiff.Difference, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureHelmValueDiff) GetDifference() HelmValueDifference {
	return v.Difference
}

// GetDiff returns GetFeatureLogTenantEnvironmentFeatureHelmValueDiff.Diff, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureHelmValueDiff) GetDiff() string { return v.Diff }

// GetFeatureLogTenantEnvironmentFeatureStatus includes the requested fields of the GraphQL type Status.
type GetFeatureLogTenantEnvironmentFeatureStatus struct {
	Version      string                                                   `json:"version"`
	Status       RolloutStatus                                            `json:"status"`
	LastModified string                                                   `json:"lastModified"`
	Log          []*GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine `json:"log"`
}

// GetVersion returns GetFeatureLogTenantEnvironmentFeatureStatus.Version, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatus) GetVersion() string { return v.Version }

// GetStatus returns GetFeatureLogTenantEnvironmentFeatureStatus.Status, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatus) GetStatus() RolloutStatus { return v.Status }

// GetLastModified returns GetFeatureLogTenantEnvironmentFeatureStatus.LastModified, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatus) GetLastModified() string { return v.LastModified }

// GetLog returns GetFeatureLogTenantEnvironmentFeatureStatus.Log, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatus) GetLog() []*GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine {
	return v.Log
}

// GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine includes the requested fields of the GraphQL type LogLine.
type GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine struct {
	Timestamp string `json:"timestamp"`
	Message   string `json:"message"`
}

// GetTimestamp returns GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine.Timestamp, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine) GetTimestamp() string {
	return v.Timestamp
}

// GetMessage returns GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine.Message, and is useful for accessing the field via an interface.
func (v *GetFeatureLogTenantEnvironmentFeatureStatusLogLogLine) GetMessage() string { return v.Message }

// GetFeatureStatusResponse is returned by GetFeatureStatus on success.
type GetFeatureStatusResponse struct {
	Tenants []*GetFeatureStatusTenantsTenant `json:"tenants"`
}

// GetTenants returns GetFeatureStatusResponse.Tenants, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusResponse) GetTenants() []*GetFeatureStatusTenantsTenant { return v.Tenants }

// GetFeatureStatusTenantsTenant includes the requested fields of the GraphQL type Tenant.
type GetFeatureStatusTenantsTenant struct {
	Name         string                                                  `json:"name"`
	Environments []*GetFeatureStatusTenantsTenantEnvironmentsEnvironment `json:"environments"`
}

// GetName returns GetFeatureStatusTenantsTenant.Name, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenant) GetName() string { return v.Name }

// GetEnvironments returns GetFeatureStatusTenantsTenant.Environments, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenant) GetEnvironments() []*GetFeatureStatusTenantsTenantEnvironmentsEnvironment {
	return v.Environments
}

// GetFeatureStatusTenantsTenantEnvironmentsEnvironment includes the requested fields of the GraphQL type Environment.
type GetFeatureStatusTenantsTenantEnvironmentsEnvironment struct {
	Name     string                                                                 `json:"name"`
	Kind     EnvironmentKind                                                        `json:"kind"`
	Features []*GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature `json:"features"`
}

// GetName returns GetFeatureStatusTenantsTenantEnvironmentsEnvironment.Name, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironment) GetName() string { return v.Name }

// GetKind returns GetFeatureStatusTenantsTenantEnvironmentsEnvironment.Kind, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironment) GetKind() EnvironmentKind {
	return v.Kind
}

// GetFeatures returns GetFeatureStatusTenantsTenantEnvironmentsEnvironment.Features, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironment) GetFeatures() []*GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature {
	return v.Features
}

// GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature includes the requested fields of the GraphQL type Feature.
type GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature struct {
	Name  string                                                                    `json:"name"`
	State *GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState `json:"state"`
}

// GetName returns GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature.Name, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature) GetName() string {
	return v.Name
}

// GetState returns GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature.State, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeature) GetState() *GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState {
	return v.State
}

// GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState includes the requested fields of the GraphQL type FeatureState.
type GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState struct {
	Enabled bool `json:"enabled"`
}

// GetEnabled returns GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState.Enabled, and is useful for accessing the field via an interface.
func (v *GetFeatureStatusTenantsTenantEnvironmentsEnvironmentFeaturesFeatureState) GetEnabled() bool {
	return v.Enabled
}

// GetFeaturesFeaturesFeature includes the requested fields of the GraphQL type Feature.
type GetFeaturesFeaturesFeature struct {
	Name             string                                              `json:"name"`
	Chart            string                                              `json:"chart"`
	Version          string                                              `json:"version"`
	Source           string                                              `json:"source"`
	Description      string                                              `json:"description"`
	EnvironmentKinds []EnvironmentKind                                   `json:"environmentKinds"`
	Dependencies     []*GetFeaturesFeaturesFeatureDependenciesDependency `json:"dependencies"`
}

// GetName returns GetFeaturesFeaturesFeature.Name, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetName() string { return v.Name }

// GetChart returns GetFeaturesFeaturesFeature.Chart, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetChart() string { return v.Chart }

// GetVersion returns GetFeaturesFeaturesFeature.Version, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetVersion() string { return v.Version }

// GetSource returns GetFeaturesFeaturesFeature.Source, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetSource() string { return v.Source }

// GetDescription returns GetFeaturesFeaturesFeature.Description, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetDescription() string { return v.Description }

// GetEnvironmentKinds returns GetFeaturesFeaturesFeature.EnvironmentKinds, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetEnvironmentKinds() []EnvironmentKind {
	return v.EnvironmentKinds
}

// GetDependencies returns GetFeaturesFeaturesFeature.Dependencies, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeature) GetDependencies() []*GetFeaturesFeaturesFeatureDependenciesDependency {
	return v.Dependencies
}

// GetFeaturesFeaturesFeatureDependenciesDependency includes the requested fields of the GraphQL type Dependency.
type GetFeaturesFeaturesFeatureDependenciesDependency struct {
	AnyOf []string `json:"anyOf"`
	AllOf []string `json:"allOf"`
}

// GetAnyOf returns GetFeaturesFeaturesFeatureDependenciesDependency.AnyOf, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeatureDependenciesDependency) GetAnyOf() []string { return v.AnyOf }

// GetAllOf returns GetFeaturesFeaturesFeatureDependenciesDependency.AllOf, and is useful for accessing the field via an interface.
func (v *GetFeaturesFeaturesFeatureDependenciesDependency) GetAllOf() []string { return v.AllOf }

// GetFeaturesResponse is returned by GetFeatures on success.
type GetFeaturesResponse struct {
	Features []*GetFeaturesFeaturesFeature `json:"features"`
}

// GetFeatures returns GetFeaturesResponse.Features, and is useful for accessing the field via an interface.
func (v *GetFeaturesResponse) GetFeatures() []*GetFeaturesFeaturesFeature { return v.Features }

// GetHelmValuesResponse is returned by GetHelmValues on success.
type GetHelmValuesResponse struct {
	// Returns the raw helm values for a feature. Requires the feature name, and either the environment ID or the environment and tenant name.
	HelmValues json.RawMessage `json:"helmValues"`
}

// GetHelmValues returns GetHelmValuesResponse.HelmValues, and is useful for accessing the field via an interface.
func (v *GetHelmValuesResponse) GetHelmValues() json.RawMessage { return v.HelmValues }

// GetRolloutResponse is returned by GetRollout on success.
type GetRolloutResponse struct {
	Rollout *GetRolloutRollout `json:"rollout"`
}

// GetRollout returns GetRolloutResponse.Rollout, and is useful for accessing the field via an interface.
func (v *GetRolloutResponse) GetRollout() *GetRolloutRollout { return v.Rollout }

// GetRolloutRollout includes the requested fields of the GraphQL type Rollout.
type GetRolloutRollout struct {
	Id          string                                 `json:"id"`
	Version     string                                 `json:"version"`
	Created     string                                 `json:"created"`
	Completed   *string                                `json:"completed"`
	Status      RolloutStatus                          `json:"status"`
	FeatureName string                                 `json:"featureName"`
	Events      []*GetRolloutRolloutEventsRolloutEvent `json:"events"`
	Logs        []*GetRolloutRolloutLogsRolloutLog     `json:"logs"`
}

// GetId returns GetRolloutRollout.Id, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetId() string { return v.Id }

// GetVersion returns GetRolloutRollout.Version, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetVersion() string { return v.Version }

// GetCreated returns GetRolloutRollout.Created, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetCreated() string { return v.Created }

// GetCompleted returns GetRolloutRollout.Completed, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetCompleted() *string { return v.Completed }

// GetStatus returns GetRolloutRollout.Status, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetStatus() RolloutStatus { return v.Status }

// GetFeatureName returns GetRolloutRollout.FeatureName, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetFeatureName() string { return v.FeatureName }

// GetEvents returns GetRolloutRollout.Events, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetEvents() []*GetRolloutRolloutEventsRolloutEvent { return v.Events }

// GetLogs returns GetRolloutRollout.Logs, and is useful for accessing the field via an interface.
func (v *GetRolloutRollout) GetLogs() []*GetRolloutRolloutLogsRolloutLog { return v.Logs }

// GetRolloutRolloutEventsRolloutEvent includes the requested fields of the GraphQL type RolloutEvent.
type GetRolloutRolloutEventsRolloutEvent struct {
	Id      string `json:"id"`
	Failure bool   `json:"failure"`
	Message string `json:"message"`
	Created string `json:"created"`
}

// GetId returns GetRolloutRolloutEventsRolloutEvent.Id, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutEventsRolloutEvent) GetId() string { return v.Id }

// GetFailure returns GetRolloutRolloutEventsRolloutEvent.Failure, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutEventsRolloutEvent) GetFailure() bool { return v.Failure }

// GetMessage returns GetRolloutRolloutEventsRolloutEvent.Message, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutEventsRolloutEvent) GetMessage() string { return v.Message }

// GetCreated returns GetRolloutRolloutEventsRolloutEvent.Created, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutEventsRolloutEvent) GetCreated() string { return v.Created }

// GetRolloutRolloutLogsRolloutLog includes the requested fields of the GraphQL type RolloutLog.
type GetRolloutRolloutLogsRolloutLog struct {
	TenantName  string                                         `json:"tenantName"`
	Environment string                                         `json:"environment"`
	Lines       []*GetRolloutRolloutLogsRolloutLogLinesLogLine `json:"lines"`
}

// GetTenantName returns GetRolloutRolloutLogsRolloutLog.TenantName, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutLogsRolloutLog) GetTenantName() string { return v.TenantName }

// GetEnvironment returns GetRolloutRolloutLogsRolloutLog.Environment, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutLogsRolloutLog) GetEnvironment() string { return v.Environment }

// GetLines returns GetRolloutRolloutLogsRolloutLog.Lines, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutLogsRolloutLog) GetLines() []*GetRolloutRolloutLogsRolloutLogLinesLogLine {
	return v.Lines
}

// GetRolloutRolloutLogsRolloutLogLinesLogLine includes the requested fields of the GraphQL type LogLine.
type GetRolloutRolloutLogsRolloutLogLinesLogLine struct {
	Timestamp string `json:"timestamp"`
	Message   string `json:"message"`
}

// GetTimestamp returns GetRolloutRolloutLogsRolloutLogLinesLogLine.Timestamp, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutLogsRolloutLogLinesLogLine) GetTimestamp() string { return v.Timestamp }

// GetMessage returns GetRolloutRolloutLogsRolloutLogLinesLogLine.Message, and is useful for accessing the field via an interface.
func (v *GetRolloutRolloutLogsRolloutLogLinesLogLine) GetMessage() string { return v.Message }

// GetRolloutsListResponse is returned by GetRolloutsList on success.
type GetRolloutsListResponse struct {
	Rollouts []*GetRolloutsListRolloutsRollout `json:"rollouts"`
}

// GetRollouts returns GetRolloutsListResponse.Rollouts, and is useful for accessing the field via an interface.
func (v *GetRolloutsListResponse) GetRollouts() []*GetRolloutsListRolloutsRollout { return v.Rollouts }

// GetRolloutsListRolloutsRollout includes the requested fields of the GraphQL type Rollout.
type GetRolloutsListRolloutsRollout struct {
	FeatureName string        `json:"featureName"`
	Version     string        `json:"version"`
	Status      RolloutStatus `json:"status"`
	Created     string        `json:"created"`
	Completed   *string       `json:"completed"`
}

// GetFeatureName returns GetRolloutsListRolloutsRollout.FeatureName, and is useful for accessing the field via an interface.
func (v *GetRolloutsListRolloutsRollout) GetFeatureName() string { return v.FeatureName }

// GetVersion returns GetRolloutsListRolloutsRollout.Version, and is useful for accessing the field via an interface.
func (v *GetRolloutsListRolloutsRollout) GetVersion() string { return v.Version }

// GetStatus returns GetRolloutsListRolloutsRollout.Status, and is useful for accessing the field via an interface.
func (v *GetRolloutsListRolloutsRollout) GetStatus() RolloutStatus { return v.Status }

// GetCreated returns GetRolloutsListRolloutsRollout.Created, and is useful for accessing the field via an interface.
func (v *GetRolloutsListRolloutsRollout) GetCreated() string { return v.Created }

// GetCompleted returns GetRolloutsListRolloutsRollout.Completed, and is useful for accessing the field via an interface.
func (v *GetRolloutsListRolloutsRollout) GetCompleted() *string { return v.Completed }

// GetRolloutsResponse is returned by GetRollouts on success.
type GetRolloutsResponse struct {
	Rollouts []*GetRolloutsRolloutsRollout `json:"rollouts"`
}

// GetRollouts returns GetRolloutsResponse.Rollouts, and is useful for accessing the field via an interface.
func (v *GetRolloutsResponse) GetRollouts() []*GetRolloutsRolloutsRollout { return v.Rollouts }

// GetRolloutsRolloutsRollout includes the requested fields of the GraphQL type Rollout.
type GetRolloutsRolloutsRollout struct {
	Id          string                                          `json:"id"`
	Version     string                                          `json:"version"`
	Created     string                                          `json:"created"`
	Completed   *string                                         `json:"completed"`
	Status      RolloutStatus                                   `json:"status"`
	FeatureName string                                          `json:"featureName"`
	Events      []*GetRolloutsRolloutsRolloutEventsRolloutEvent `json:"events"`
}

// GetId returns GetRolloutsRolloutsRollout.Id, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetId() string { return v.Id }

// GetVersion returns GetRolloutsRolloutsRollout.Version, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetVersion() string { return v.Version }

// GetCreated returns GetRolloutsRolloutsRollout.Created, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetCreated() string { return v.Created }

// GetCompleted returns GetRolloutsRolloutsRollout.Completed, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetCompleted() *string { return v.Completed }

// GetStatus returns GetRolloutsRolloutsRollout.Status, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetStatus() RolloutStatus { return v.Status }

// GetFeatureName returns GetRolloutsRolloutsRollout.FeatureName, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetFeatureName() string { return v.FeatureName }

// GetEvents returns GetRolloutsRolloutsRollout.Events, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRollout) GetEvents() []*GetRolloutsRolloutsRolloutEventsRolloutEvent {
	return v.Events
}

// GetRolloutsRolloutsRolloutEventsRolloutEvent includes the requested fields of the GraphQL type RolloutEvent.
type GetRolloutsRolloutsRolloutEventsRolloutEvent struct {
	Id      string `json:"id"`
	Failure bool   `json:"failure"`
	Message string `json:"message"`
}

// GetId returns GetRolloutsRolloutsRolloutEventsRolloutEvent.Id, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRolloutEventsRolloutEvent) GetId() string { return v.Id }

// GetFailure returns GetRolloutsRolloutsRolloutEventsRolloutEvent.Failure, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRolloutEventsRolloutEvent) GetFailure() bool { return v.Failure }

// GetMessage returns GetRolloutsRolloutsRolloutEventsRolloutEvent.Message, and is useful for accessing the field via an interface.
func (v *GetRolloutsRolloutsRolloutEventsRolloutEvent) GetMessage() string { return v.Message }

// GetTenantEnvironmentResponse is returned by GetTenantEnvironment on success.
type GetTenantEnvironmentResponse struct {
	// tenant returns the given tenant.
	Tenant *GetTenantEnvironmentTenant `json:"tenant"`
}

// GetTenant returns GetTenantEnvironmentResponse.Tenant, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentResponse) GetTenant() *GetTenantEnvironmentTenant { return v.Tenant }

// GetTenantEnvironmentTenant includes the requested fields of the GraphQL type Tenant.
type GetTenantEnvironmentTenant struct {
	Id          string                                 `json:"id"`
	Name        string                                 `json:"name"`
	Environment *GetTenantEnvironmentTenantEnvironment `json:"environment"`
}

// GetId returns GetTenantEnvironmentTenant.Id, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenant) GetId() string { return v.Id }

// GetName returns GetTenantEnvironmentTenant.Name, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenant) GetName() string { return v.Name }

// GetEnvironment returns GetTenantEnvironmentTenant.Environment, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenant) GetEnvironment() *GetTenantEnvironmentTenantEnvironment {
	return v.Environment
}

// GetTenantEnvironmentTenantEnvironment includes the requested fields of the GraphQL type Environment.
type GetTenantEnvironmentTenantEnvironment struct {
	Id           string                                                         `json:"id"`
	Name         string                                                         `json:"name"`
	Description  *string                                                        `json:"description"`
	Created      string                                                         `json:"created"`
	LastModified string                                                         `json:"lastModified"`
	Kind         EnvironmentKind                                                `json:"kind"`
	GcpProjectID *string                                                        `json:"gcpProjectID"`
	Reconcile    bool                                                           `json:"reconcile"`
	Features     []*GetTenantEnvironmentTenantEnvironmentFeaturesFeature        `json:"features"`
	Values       []*GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue `json:"values"`
}

// GetId returns GetTenantEnvironmentTenantEnvironment.Id, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetId() string { return v.Id }

// GetName returns GetTenantEnvironmentTenantEnvironment.Name, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetName() string { return v.Name }

// GetDescription returns GetTenantEnvironmentTenantEnvironment.Description, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetDescription() *string { return v.Description }

// GetCreated returns GetTenantEnvironmentTenantEnvironment.Created, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetCreated() string { return v.Created }

// GetLastModified returns GetTenantEnvironmentTenantEnvironment.LastModified, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetLastModified() string { return v.LastModified }

// GetKind returns GetTenantEnvironmentTenantEnvironment.Kind, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetKind() EnvironmentKind { return v.Kind }

// GetGcpProjectID returns GetTenantEnvironmentTenantEnvironment.GcpProjectID, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetGcpProjectID() *string { return v.GcpProjectID }

// GetReconcile returns GetTenantEnvironmentTenantEnvironment.Reconcile, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetReconcile() bool { return v.Reconcile }

// GetFeatures returns GetTenantEnvironmentTenantEnvironment.Features, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetFeatures() []*GetTenantEnvironmentTenantEnvironmentFeaturesFeature {
	return v.Features
}

// GetValues returns GetTenantEnvironmentTenantEnvironment.Values, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironment) GetValues() []*GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue {
	return v.Values
}

// GetTenantEnvironmentTenantEnvironmentFeaturesFeature includes the requested fields of the GraphQL type Feature.
type GetTenantEnvironmentTenantEnvironmentFeaturesFeature struct {
	Name             string                                                     `json:"name"`
	EnvironmentKinds []EnvironmentKind                                          `json:"environmentKinds"`
	State            *GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState `json:"state"`
}

// GetName returns GetTenantEnvironmentTenantEnvironmentFeaturesFeature.Name, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentFeaturesFeature) GetName() string { return v.Name }

// GetEnvironmentKinds returns GetTenantEnvironmentTenantEnvironmentFeaturesFeature.EnvironmentKinds, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentFeaturesFeature) GetEnvironmentKinds() []EnvironmentKind {
	return v.EnvironmentKinds
}

// GetState returns GetTenantEnvironmentTenantEnvironmentFeaturesFeature.State, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentFeaturesFeature) GetState() *GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState {
	return v.State
}

// GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState includes the requested fields of the GraphQL type FeatureState.
type GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState struct {
	Enabled bool `json:"enabled"`
}

// GetEnabled returns GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState.Enabled, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentFeaturesFeatureState) GetEnabled() bool {
	return v.Enabled
}

// GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue includes the requested fields of the GraphQL type EnvironmentValue.
type GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

// GetKey returns GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue.Key, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue) GetKey() string { return v.Key }

// GetValue returns GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue.Value, and is useful for accessing the field via an interface.
func (v *GetTenantEnvironmentTenantEnvironmentValuesEnvironmentValue) GetValue() json.RawMessage {
	return v.Value
}

// GetTenantOverviewResponse is returned by GetTenantOverview on success.
type GetTenantOverviewResponse struct {
	// tenant returns the given tenant.
	Tenant *GetTenantOverviewTenant `json:"tenant"`
}

// GetTenant returns GetTenantOverviewResponse.Tenant, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewResponse) GetTenant() *GetTenantOverviewTenant { return v.Tenant }

// GetTenantOverviewTenant includes the requested fields of the GraphQL type Tenant.
type GetTenantOverviewTenant struct {
	Id           string                                            `json:"id"`
	Name         string                                            `json:"name"`
	Environments []*GetTenantOverviewTenantEnvironmentsEnvironment `json:"environments"`
}

// GetId returns GetTenantOverviewTenant.Id, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenant) GetId() string { return v.Id }

// GetName returns GetTenantOverviewTenant.Name, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenant) GetName() string { return v.Name }

// GetEnvironments returns GetTenantOverviewTenant.Environments, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenant) GetEnvironments() []*GetTenantOverviewTenantEnvironmentsEnvironment {
	return v.Environments
}

// GetTenantOverviewTenantEnvironmentsEnvironment includes the requested fields of the GraphQL type Environment.
type GetTenantOverviewTenantEnvironmentsEnvironment struct {
	Id           string                                                           `json:"id"`
	Name         string                                                           `json:"name"`
	Description  *string                                                          `json:"description"`
	Created      string                                                           `json:"created"`
	LastModified string                                                           `json:"lastModified"`
	Kind         EnvironmentKind                                                  `json:"kind"`
	GcpProjectID *string                                                          `json:"gcpProjectID"`
	Reconcile    bool                                                             `json:"reconcile"`
	Features     []*GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature `json:"features"`
}

// GetId returns GetTenantOverviewTenantEnvironmentsEnvironment.Id, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetId() string { return v.Id }

// GetName returns GetTenantOverviewTenantEnvironmentsEnvironment.Name, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetName() string { return v.Name }

// GetDescription returns GetTenantOverviewTenantEnvironmentsEnvironment.Description, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetDescription() *string {
	return v.Description
}

// GetCreated returns GetTenantOverviewTenantEnvironmentsEnvironment.Created, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetCreated() string { return v.Created }

// GetLastModified returns GetTenantOverviewTenantEnvironmentsEnvironment.LastModified, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetLastModified() string {
	return v.LastModified
}

// GetKind returns GetTenantOverviewTenantEnvironmentsEnvironment.Kind, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetKind() EnvironmentKind { return v.Kind }

// GetGcpProjectID returns GetTenantOverviewTenantEnvironmentsEnvironment.GcpProjectID, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetGcpProjectID() *string {
	return v.GcpProjectID
}

// GetReconcile returns GetTenantOverviewTenantEnvironmentsEnvironment.Reconcile, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetReconcile() bool { return v.Reconcile }

// GetFeatures returns GetTenantOverviewTenantEnvironmentsEnvironment.Features, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironment) GetFeatures() []*GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature {
	return v.Features
}

// GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature includes the requested fields of the GraphQL type Feature.
type GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature struct {
	Name string `json:"name"`
}

// GetName returns GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature.Name, and is useful for accessing the field via an interface.
func (v *GetTenantOverviewTenantEnvironmentsEnvironmentFeaturesFeature) GetName() string {
	return v.Name
}

// GetTenantsResponse is returned by GetTenants on success.
type GetTenantsResponse struct {
	Tenants []*GetTenantsTenantsTenant `json:"tenants"`
}

// GetTenants returns GetTenantsResponse.Tenants, and is useful for accessing the field via an interface.
func (v *GetTenantsResponse) GetTenants() []*GetTenantsTenantsTenant { return v.Tenants }

// GetTenantsTenantsTenant includes the requested fields of the GraphQL type Tenant.
type GetTenantsTenantsTenant struct {
	Id           string                                            `json:"id"`
	Name         string                                            `json:"name"`
	Environments []*GetTenantsTenantsTenantEnvironmentsEnvironment `json:"environments"`
}

// GetId returns GetTenantsTenantsTenant.Id, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenant) GetId() string { return v.Id }

// GetName returns GetTenantsTenantsTenant.Name, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenant) GetName() string { return v.Name }

// GetEnvironments returns GetTenantsTenantsTenant.Environments, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenant) GetEnvironments() []*GetTenantsTenantsTenantEnvironmentsEnvironment {
	return v.Environments
}

// GetTenantsTenantsTenantEnvironmentsEnvironment includes the requested fields of the GraphQL type Environment.
type GetTenantsTenantsTenantEnvironmentsEnvironment struct {
	Id           string          `json:"id"`
	Name         string          `json:"name"`
	Description  *string         `json:"description"`
	Created      string          `json:"created"`
	LastModified string          `json:"lastModified"`
	Kind         EnvironmentKind `json:"kind"`
	GcpProjectID *string         `json:"gcpProjectID"`
	Reconcile    bool            `json:"reconcile"`
}

// GetId returns GetTenantsTenantsTenantEnvironmentsEnvironment.Id, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetId() string { return v.Id }

// GetName returns GetTenantsTenantsTenantEnvironmentsEnvironment.Name, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetName() string { return v.Name }

// GetDescription returns GetTenantsTenantsTenantEnvironmentsEnvironment.Description, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetDescription() *string {
	return v.Description
}

// GetCreated returns GetTenantsTenantsTenantEnvironmentsEnvironment.Created, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetCreated() string { return v.Created }

// GetLastModified returns GetTenantsTenantsTenantEnvironmentsEnvironment.LastModified, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetLastModified() string {
	return v.LastModified
}

// GetKind returns GetTenantsTenantsTenantEnvironmentsEnvironment.Kind, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetKind() EnvironmentKind { return v.Kind }

// GetGcpProjectID returns GetTenantsTenantsTenantEnvironmentsEnvironment.GcpProjectID, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetGcpProjectID() *string {
	return v.GcpProjectID
}

// GetReconcile returns GetTenantsTenantsTenantEnvironmentsEnvironment.Reconcile, and is useful for accessing the field via an interface.
func (v *GetTenantsTenantsTenantEnvironmentsEnvironment) GetReconcile() bool { return v.Reconcile }

type HelmValueDifference string

const (
	HelmValueDifferenceFullMatch     HelmValueDifference = "FULL_MATCH"
	HelmValueDifferenceSupersetMatch HelmValueDifference = "SUPERSET_MATCH"
	HelmValueDifferenceNoMatch       HelmValueDifference = "NO_MATCH"
	HelmValueDifferenceInvalidJson   HelmValueDifference = "INVALID_JSON"
)

var AllHelmValueDifference = []HelmValueDifference{
	HelmValueDifferenceFullMatch,
	HelmValueDifferenceSupersetMatch,
	HelmValueDifferenceNoMatch,
	HelmValueDifferenceInvalidJson,
}

type NewConfiguration struct {
	EnvironmentID *string         `json:"environmentID"`
	Feature       string          `json:"feature"`
	Description   *string         `json:"description"`
	Key           string          `json:"key"`
	Value         json.RawMessage `json:"value"`
}

// GetEnvironmentID returns NewConfiguration.EnvironmentID, and is useful for accessing the field via an interface.
func (v *NewConfiguration) GetEnvironmentID() *string { return v.EnvironmentID }

// GetFeature returns NewConfiguration.Feature, and is useful for accessing the field via an interface.
func (v *NewConfiguration) GetFeature() string { return v.Feature }

// GetDescription returns NewConfiguration.Description, and is useful for accessing the field via an interface.
func (v *NewConfiguration) GetDescription() *string { return v.Description }

// GetKey returns NewConfiguration.Key, and is useful for accessing the field via an interface.
func (v *NewConfiguration) GetKey() string { return v.Key }

// GetValue returns NewConfiguration.Value, and is useful for accessing the field via an interface.
func (v *NewConfiguration) GetValue() json.RawMessage { return v.Value }

type RolloutStatus string

const (
	RolloutStatusUnknown  RolloutStatus = "UNKNOWN"
	RolloutStatusCreated  RolloutStatus = "CREATED"
	RolloutStatusPending  RolloutStatus = "PENDING"
	RolloutStatusDeployed RolloutStatus = "DEPLOYED"
	RolloutStatusFailed   RolloutStatus = "FAILED"
)

var AllRolloutStatus = []RolloutStatus{
	RolloutStatusUnknown,
	RolloutStatusCreated,
	RolloutStatusPending,
	RolloutStatusDeployed,
	RolloutStatusFailed,
}

// SetFeatureStateMutationFeatureStateSaveFeatureState includes the requested fields of the GraphQL type FeatureState.
type SetFeatureStateMutationFeatureStateSaveFeatureState struct {
	Id      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

// GetId returns SetFeatureStateMutationFeatureStateSaveFeatureState.Id, and is useful for accessing the field via an interface.
func (v *SetFeatureStateMutationFeatureStateSaveFeatureState) GetId() string { return v.Id }

// GetEnabled returns SetFeatureStateMutationFeatureStateSaveFeatureState.Enabled, and is useful for accessing the field via an interface.
func (v *SetFeatureStateMutationFeatureStateSaveFeatureState) GetEnabled() bool { return v.Enabled }

// SetFeatureStateMutationResponse is returned by SetFeatureStateMutation on success.
type SetFeatureStateMutationResponse struct {
	FeatureStateSave *SetFeatureStateMutationFeatureStateSaveFeatureState `json:"featureStateSave"`
}

// GetFeatureStateSave returns SetFeatureStateMutationResponse.FeatureStateSave, and is useful for accessing the field via an interface.
func (v *SetFeatureStateMutationResponse) GetFeatureStateSave() *SetFeatureStateMutationFeatureStateSaveFeatureState {
	return v.FeatureStateSave
}

type UpdateConfiguration struct {
	Description *string         `json:"description"`
	Value       json.RawMessage `json:"value"`
}

// GetDescription returns UpdateConfiguration.Description, and is useful for accessing the field via an interface.
func (v *UpdateConfiguration) GetDescription() *string { return v.Description }

// GetValue returns UpdateConfiguration.Value, and is useful for accessing the field via an interface.
func (v *UpdateConfiguration) GetValue() json.RawMessage { return v.Value }

// UpdateConfigurationMutationConfigurationUpdateConfiguration includes the requested fields of the GraphQL type Configuration.
type UpdateConfigurationMutationConfigurationUpdateConfiguration struct {
	Id      string                                                            `json:"id"`
	Value   *UpdateConfigurationMutationConfigurationUpdateConfigurationValue `json:"value"`
	Content *json.RawMessage                                                  `json:"content"`
}

// GetId returns UpdateConfigurationMutationConfigurationUpdateConfiguration.Id, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationConfigurationUpdateConfiguration) GetId() string { return v.Id }

// GetValue returns UpdateConfigurationMutationConfigurationUpdateConfiguration.Value, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationConfigurationUpdateConfiguration) GetValue() *UpdateConfigurationMutationConfigurationUpdateConfigurationValue {
	return v.Value
}

// GetContent returns UpdateConfigurationMutationConfigurationUpdateConfiguration.Content, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationConfigurationUpdateConfiguration) GetContent() *json.RawMessage {
	return v.Content
}

// UpdateConfigurationMutationConfigurationUpdateConfigurationValue includes the requested fields of the GraphQL type Value.
type UpdateConfigurationMutationConfigurationUpdateConfigurationValue struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
}

// GetKey returns UpdateConfigurationMutationConfigurationUpdateConfigurationValue.Key, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationConfigurationUpdateConfigurationValue) GetKey() string {
	return v.Key
}

// GetDisplayName returns UpdateConfigurationMutationConfigurationUpdateConfigurationValue.DisplayName, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationConfigurationUpdateConfigurationValue) GetDisplayName() string {
	return v.DisplayName
}

// UpdateConfigurationMutationResponse is returned by UpdateConfigurationMutation on success.
type UpdateConfigurationMutationResponse struct {
	ConfigurationUpdate *UpdateConfigurationMutationConfigurationUpdateConfiguration `json:"configurationUpdate"`
}

// GetConfigurationUpdate returns UpdateConfigurationMutationResponse.ConfigurationUpdate, and is useful for accessing the field via an interface.
func (v *UpdateConfigurationMutationResponse) GetConfigurationUpdate() *UpdateConfigurationMutationConfigurationUpdateConfiguration {
	return v.ConfigurationUpdate
}

// __CreateConfigurationMutationInput is used internally by genqlient
type __CreateConfigurationMutationInput struct {
	Configuration *NewConfiguration `json:"configuration,omitempty"`
}

// GetConfiguration returns __CreateConfigurationMutationInput.Configuration, and is useful for accessing the field via an interface.
func (v *__CreateConfigurationMutationInput) GetConfiguration() *NewConfiguration {
	return v.Configuration
}

// __GetDeploymentDetailInput is used internally by genqlient
type __GetDeploymentDetailInput struct {
	Id string `json:"id"`
}

// GetId returns __GetDeploymentDetailInput.Id, and is useful for accessing the field via an interface.
func (v *__GetDeploymentDetailInput) GetId() string { return v.Id }

// __GetDeploymentsInput is used internally by genqlient
type __GetDeploymentsInput struct {
	Feature string `json:"feature"`
}

// GetFeature returns __GetDeploymentsInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetDeploymentsInput) GetFeature() string { return v.Feature }

// __GetFeatureConfigInput is used internally by genqlient
type __GetFeatureConfigInput struct {
	Feature string  `json:"feature"`
	EnvID   *string `json:"envID"`
}

// GetFeature returns __GetFeatureConfigInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetFeatureConfigInput) GetFeature() string { return v.Feature }

// GetEnvID returns __GetFeatureConfigInput.EnvID, and is useful for accessing the field via an interface.
func (v *__GetFeatureConfigInput) GetEnvID() *string { return v.EnvID }

// __GetFeatureLogInput is used internally by genqlient
type __GetFeatureLogInput struct {
	Tenant  string `json:"tenant"`
	Env     string `json:"env"`
	Feature string `json:"feature"`
}

// GetTenant returns __GetFeatureLogInput.Tenant, and is useful for accessing the field via an interface.
func (v *__GetFeatureLogInput) GetTenant() string { return v.Tenant }

// GetEnv returns __GetFeatureLogInput.Env, and is useful for accessing the field via an interface.
func (v *__GetFeatureLogInput) GetEnv() string { return v.Env }

// GetFeature returns __GetFeatureLogInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetFeatureLogInput) GetFeature() string { return v.Feature }

// __GetHelmValuesInput is used internally by genqlient
type __GetHelmValuesInput struct {
	Feature string  `json:"feature"`
	EnvID   *string `json:"envID"`
	Tenant  *string `json:"tenant"`
	Env     *string `json:"env"`
}

// GetFeature returns __GetHelmValuesInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetHelmValuesInput) GetFeature() string { return v.Feature }

// GetEnvID returns __GetHelmValuesInput.EnvID, and is useful for accessing the field via an interface.
func (v *__GetHelmValuesInput) GetEnvID() *string { return v.EnvID }

// GetTenant returns __GetHelmValuesInput.Tenant, and is useful for accessing the field via an interface.
func (v *__GetHelmValuesInput) GetTenant() *string { return v.Tenant }

// GetEnv returns __GetHelmValuesInput.Env, and is useful for accessing the field via an interface.
func (v *__GetHelmValuesInput) GetEnv() *string { return v.Env }

// __GetRolloutInput is used internally by genqlient
type __GetRolloutInput struct {
	Feature string `json:"feature"`
	Version string `json:"version"`
}

// GetFeature returns __GetRolloutInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetRolloutInput) GetFeature() string { return v.Feature }

// GetVersion returns __GetRolloutInput.Version, and is useful for accessing the field via an interface.
func (v *__GetRolloutInput) GetVersion() string { return v.Version }

// __GetRolloutsInput is used internally by genqlient
type __GetRolloutsInput struct {
	Feature string `json:"feature"`
}

// GetFeature returns __GetRolloutsInput.Feature, and is useful for accessing the field via an interface.
func (v *__GetRolloutsInput) GetFeature() string { return v.Feature }

// __GetTenantEnvironmentInput is used internally by genqlient
type __GetTenantEnvironmentInput struct {
	Slug string `json:"slug"`
	Env  string `json:"env"`
}

// GetSlug returns __GetTenantEnvironmentInput.Slug, and is useful for accessing the field via an interface.
func (v *__GetTenantEnvironmentInput) GetSlug() string { return v.Slug }

// GetEnv returns __GetTenantEnvironmentInput.Env, and is useful for accessing the field via an interface.
func (v *__GetTenantEnvironmentInput) GetEnv() string { return v.Env }

// __GetTenantOverviewInput is used internally by genqlient
type __GetTenantOverviewInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __GetTenantOverviewInput.Slug, and is useful for accessing the field via an interface.
func (v *__GetTenantOverviewInput) GetSlug() string { return v.Slug }

// __SetFeatureStateMutationInput is used internally by genqlient
type __SetFeatureStateMutationInput struct {
	EnvID   string `json:"envID"`
	Feature string `json:"feature"`
	Enabled bool   `json:"enabled"`
}

// GetEnvID returns __SetFeatureStateMutationInput.EnvID, and is useful for accessing the field via an interface.
func (v *__SetFeatureStateMutationInput) GetEnvID() string { return v.EnvID }

// GetFeature returns __SetFeatureStateMutationInput.Feature, and is useful for accessing the field via an interface.
func (v *__SetFeatureStateMutationInput) GetFeature() string { return v.Feature }

// GetEnabled returns __SetFeatureStateMutationInput.Enabled, and is useful for accessing the field via an interface.
func (v *__SetFeatureStateMutationInput) GetEnabled() bool { return v.Enabled }

// __UpdateConfigurationMutationInput is used internally by genqlient
type __UpdateConfigurationMutationInput struct {
	Id            string               `json:"id"`
	Configuration *UpdateConfiguration `json:"configuration,omitempty"`
}

// GetId returns __UpdateConfigurationMutationInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateConfigurationMutationInput) GetId() string { return v.Id }

// GetConfiguration returns __UpdateConfigurationMutationInput.Configuration, and is useful for accessing the field via an interface.
func (v *__UpdateConfigurationMutationInput) GetConfiguration() *UpdateConfiguration {
	return v.Configuration
}

// The mutation executed by CreateConfigurationMutation.
const CreateConfigurationMutation_Operation = `
mutation CreateConfigurationMutation ($configuration: NewConfiguration!) {
	configurationCreate(configuration: $configuration) {
		id
		value {
			key
			displayName
		}
		content
		source
	}
}
`

// Create configuration override
func CreateConfigurationMutation(
	ctx_ context.Context,
	client_ graphql.Client,
	configuration *NewConfiguration,
) (data_ *CreateConfigurationMutationResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateConfigurationMutation",
		Query:  CreateConfigurationMutation_Operation,
		Variables: &__CreateConfigurationMutationInput{
			Configuration: configuration,
		},
	}

	data_ = &CreateConfigurationMutationResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDeploymentDetail.
const GetDeploymentDetail_Operation = `
query GetDeploymentDetail ($id: ID!) {
	deployment(id: $id) {
		id
		feature {
			name
			version
		}
		target {
			key
			value
		}
		created
		ci
		description
		statuses {
			state
			message
			lastModified
			environment {
				name
				tenant {
					name
				}
			}
		}
	}
}
`

// Single deployment detail
func GetDeploymentDetail(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetDeploymentDetailResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDeploymentDetail",
		Query:  GetDeploymentDetail_Operation,
		Variables: &__GetDeploymentDetailInput{
			Id: id,
		},
	}

	data_ = &GetDeploymentDetailResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDeployments.
const GetDeployments_Operation = `
query GetDeployments ($feature: String!) {
	deployments(feature: $feature) {
		id
		feature {
			name
			version
		}
		target {
			key
			value
		}
		created
		ci
		statuses {
			state
		}
	}
}
`

// Deployments for a specific feature (for feature rollouts tab)
func GetDeployments(
	ctx_ context.Context,
	client_ graphql.Client,
	feature string,
) (data_ *GetDeploymentsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDeployments",
		Query:  GetDeployments_Operation,
		Variables: &__GetDeploymentsInput{
			Feature: feature,
		},
	}

	data_ = &GetDeploymentsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDeploymentsList.
const GetDeploymentsList_Operation = `
query GetDeploymentsList {
	deployments {
		id
		feature {
			name
			version
		}
		target {
			key
			value
		}
		created
		ci
		statuses {
			state
		}
	}
}
`

// Deployments listing query (lightweight, for global rollouts page)
func GetDeploymentsList(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetDeploymentsListResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDeploymentsList",
		Query:  GetDeploymentsList_Operation,
	}

	data_ = &GetDeploymentsListResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetFeatureConfig.
const GetFeatureConfig_Operation = `
query GetFeatureConfig ($feature: String!, $envID: ID) {
	configuration(feature: $feature, envID: $envID) {
		configuration {
			id
			value {
				key
				displayName
				description
				required
				config {
					type
					secret
				}
				computed {
					template
				}
			}
			content
			source
		}
	}
}
`

// Feature configuration query (on-demand, not cached)
func GetFeatureConfig(
	ctx_ context.Context,
	client_ graphql.Client,
	feature string,
	envID *string,
) (data_ *GetFeatureConfigResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetFeatureConfig",
		Query:  GetFeatureConfig_Operation,
		Variables: &__GetFeatureConfigInput{
			Feature: feature,
			EnvID:   envID,
		},
	}

	data_ = &GetFeatureConfigResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetFeatureLog.
const GetFeatureLog_Operation = `
query GetFeatureLog ($tenant: String!, $env: String!, $feature: String!) {
	tenant(slug: $tenant) {
		environment(slug: $env) {
			feature(name: $feature) {
				name
				status {
					version
					status
					lastModified
					log {
						timestamp
						message
					}
				}
				helmValueDiff {
					difference
					diff
				}
			}
		}
	}
}
`

// Feature log for a specific tenant/environment (last rollout only)
func GetFeatureLog(
	ctx_ context.Context,
	client_ graphql.Client,
	tenant string,
	env string,
	feature string,
) (data_ *GetFeatureLogResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetFeatureLog",
		Query:  GetFeatureLog_Operation,
		Variables: &__GetFeatureLogInput{
			Tenant:  tenant,
			Env:     env,
			Feature: feature,
		},
	}

	data_ = &GetFeatureLogResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetFeatureStatus.
const GetFeatureStatus_Operation = `
query GetFeatureStatus {
	tenants {
		name
		environments {
			name
			kind
			features {
				name
				state {
					enabled
				}
			}
		}
	}
}
`

// Feature status across all tenants (single query for feature status tab)
func GetFeatureStatus(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetFeatureStatusResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetFeatureStatus",
		Query:  GetFeatureStatus_Operation,
	}

	data_ = &GetFeatureStatusResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetFeatures.
const GetFeatures_Operation = `
query GetFeatures {
	features {
		name
		chart
		version
		source
		description
		environmentKinds
		dependencies {
			anyOf
			allOf
		}
	}
}
`

// Feature queries
func GetFeatures(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetFeaturesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetFeatures",
		Query:  GetFeatures_Operation,
	}

	data_ = &GetFeaturesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetHelmValues.
const GetHelmValues_Operation = `
query GetHelmValues ($feature: String!, $envID: ID, $tenant: String, $env: String) {
	helmValues(feature: $feature, envID: $envID, tenant: $tenant, env: $env)
}
`

// Helm values query
func GetHelmValues(
	ctx_ context.Context,
	client_ graphql.Client,
	feature string,
	envID *string,
	tenant *string,
	env *string,
) (data_ *GetHelmValuesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetHelmValues",
		Query:  GetHelmValues_Operation,
		Variables: &__GetHelmValuesInput{
			Feature: feature,
			EnvID:   envID,
			Tenant:  tenant,
			Env:     env,
		},
	}

	data_ = &GetHelmValuesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetRollout.
const GetRollout_Operation = `
query GetRollout ($feature: String!, $version: String!) {
	rollout(feature: $feature, version: $version) {
		id
		version
		created
		completed
		status
		featureName
		events {
			id
			failure
			message
			created
		}
		logs {
			tenantName
			environment
			lines {
				timestamp
				message
			}
		}
	}
}
`

// Single rollout detail (with events + logs per environment)
func GetRollout(
	ctx_ context.Context,
	client_ graphql.Client,
	feature string,
	version string,
) (data_ *GetRolloutResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetRollout",
		Query:  GetRollout_Operation,
		Variables: &__GetRolloutInput{
			Feature: feature,
			Version: version,
		},
	}

	data_ = &GetRolloutResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetRollouts.
const GetRollouts_Operation = `
query GetRollouts ($feature: String!) {
	rollouts(feature: $feature) {
		id
		version
		created
		completed
		status
		featureName
		events {
			id
			failure
			message
		}
	}
}
`

// Rollouts query (with events, no logs)
func GetRollouts(
	ctx_ context.Context,
	client_ graphql.Client,
	feature string,
) (data_ *GetRolloutsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetRollouts",
		Query:  GetRollouts_Operation,
		Variables: &__GetRolloutsInput{
			Feature: feature,
		},
	}

	data_ = &GetRolloutsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetRolloutsList.
const GetRolloutsList_Operation = `
query GetRolloutsList {
	rollouts {
		featureName
		version
		status
		created
		completed
	}
}
`

// Rollouts listing query (lightweight, for global rollouts page)
func GetRolloutsList(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetRolloutsListResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetRolloutsList",
		Query:  GetRolloutsList_Operation,
	}

	data_ = &GetRolloutsListResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetTenantEnvironment.
const GetTenantEnvironment_Operation = `
query GetTenantEnvironment ($slug: String!, $env: String!) {
	tenant(slug: $slug) {
		id
		name
		environment(slug: $env) {
			id
			name
			description
			created
			lastModified
			kind
			gcpProjectID
			reconcile
			features {
				name
				environmentKinds
				state {
					enabled
				}
			}
			values {
				key
				value
			}
		}
	}
}
`

// Single environment with features (for environment/feature pages)
func GetTenantEnvironment(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
	env string,
) (data_ *GetTenantEnvironmentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetTenantEnvironment",
		Query:  GetTenantEnvironment_Operation,
		Variables: &__GetTenantEnvironmentInput{
			Slug: slug,
			Env:  env,
		},
	}

	data_ = &GetTenantEnvironmentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetTenantOverview.
const GetTenantOverview_Operation = `
query GetTenantOverview ($slug: String!) {
	tenant(slug: $slug) {
		id
		name
		environments {
			id
			name
			description
			created
			lastModified
			kind
			gcpProjectID
			reconcile
			features {
				name
			}
		}
	}
}
`

// Tenant overview (env metadata + feature names only, for tenant page and feature status)
func GetTenantOverview(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *GetTenantOverviewResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetTenantOverview",
		Query:  GetTenantOverview_Operation,
		Variables: &__GetTenantOverviewInput{
			Slug: slug,
		},
	}

	data_ = &GetTenantOverviewResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetTenants.
const GetTenants_Operation = `
query GetTenants {
	tenants {
		id
		name
		environments {
			id
			name
			description
			created
			lastModified
			kind
			gcpProjectID
			reconcile
		}
	}
}
`

// Tenant queries (lightweight - for front page and tenant listing)
func GetTenants(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetTenantsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetTenants",
		Query:  GetTenants_Operation,
	}

	data_ = &GetTenantsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by SetFeatureStateMutation.
const SetFeatureStateMutation_Operation = `
mutation SetFeatureStateMutation ($envID: ID!, $feature: String!, $enabled: Boolean!) {
	featureStateSave(envID: $envID, enabled: $enabled, feature: $feature) {
		id
		enabled
	}
}
`

// Toggle feature reconcile state
func SetFeatureStateMutation(
	ctx_ context.Context,
	client_ graphql.Client,
	envID string,
	feature string,
	enabled bool,
) (data_ *SetFeatureStateMutationResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SetFeatureStateMutation",
		Query:  SetFeatureStateMutation_Operation,
		Variables: &__SetFeatureStateMutationInput{
			EnvID:   envID,
			Feature: feature,
			Enabled: enabled,
		},
	}

	data_ = &SetFeatureStateMutationResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateConfigurationMutation.
const UpdateConfigurationMutation_Operation = `
mutation UpdateConfigurationMutation ($id: ID!, $configuration: UpdateConfiguration!) {
	configurationUpdate(id: $id, configuration: $configuration) {
		id
		value {
			key
			displayName
		}
		content
	}
}
`

// Configuration mutation
func UpdateConfigurationMutation(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
	configuration *UpdateConfiguration,
) (data_ *UpdateConfigurationMutationResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateConfigurationMutation",
		Query:  UpdateConfigurationMutation_Operation,
		Variables: &__UpdateConfigurationMutationInput{
			Id:            id,
			Configuration: configuration,
		},
	}

	data_ = &UpdateConfigurationMutationResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
