project_name: narc-cli
builds:
  - targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    id: narc
    dir: .
    main: cmd/narc/main.go
    binary: narc
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: nais
    name: narcos
  header: |
    ## narc-cli ({{ .Version }})

brews:
  - tap:
      owner: nais
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_PUSH_TOKEN }}"
    name: narc
    homepage: "https://github.com/nais/narcos"
    description: "NAIS Administration CLI"
    folder: Formula
    install: |
      bin.install "narc"
    test: |
      assert_match version, shell_output("#{bin}/narc version")
nfpms:
  - package_name: narc
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    vendor: NAV / nais team
    homepage: "https://github.com/nais/narcos"
    maintainer: NAV / nais team
    description: "NAIS Administration CLI"
    license: MIT
    formats:
      - deb
    version_metadata: git
