# typed: false
# frozen_string_literal: true

# This file was generated by nais/narcos. DO NOT EDIT.
class Narc < Formula
  desc "Admin command-line interface for Nais"
  homepage "https://github.com/nais/narcos"
  version "__VERSION__"
  version_scheme 1

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nais/narcos/releases/download/__VERSION__/narc-cli___VERSION___darwin_amd64.tar.gz"
      sha256 "__SHA_DARWIN_AMD64__"

      def install
        bin.install "narc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nais/narcos/releases/download/__VERSION__/narc-cli___VERSION___darwin_arm64.tar.gz"
      sha256 "__SHA_DARWIN_ARM64__"

      def install
        bin.install "narc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nais/narcos/releases/download/__VERSION__/narc-cli___VERSION___linux_amd64.tar.gz"
      sha256 "__SHA_LINUX_AMD64__"
      def install
        bin.install "narc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nais/narcos/releases/download/__VERSION__/narc-cli___VERSION___linux_arm64.tar.gz"
      sha256 "__SHA_LINUX_ARM64__"
      def install
        bin.install "narc"
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/narc version")
  end
end
