# typed: false
# frozen_string_literal: true

# This file was generated by nais/narcos. DO NOT EDIT.
class Narc < Formula
  desc "Admin command-line interface for Nais"
  homepage "https://github.com/nais/narcos"
  version "$VERSION"
  version_scheme 1

  on_macos do
    on_intel do
      url "$NARC_CLI_DARWIN_AMD64_URL"
      sha256 "$NARC_CLI_DARWIN_AMD64_HASH_BASE16"
    end
    on_arm do
      url "$NARC_CLI_DARWIN_ARM64_URL"
      sha256 "$NARC_CLI_DARWIN_ARM64_HASH_BASE16"
    end
  end

  on_linux do
    on_intel do
      url "$NARC_CLI_LINUX_AMD64_URL"
      sha256 "$NARC_CLI_LINUX_AMD64_HASH_BASE16"
    end
    on_arm do
      url "$NARC_CLI_LINUX_ARM64_URL"
      sha256 "$NARC_CLI_LINUX_ARM64_HASH_BASE16"
    end
  end

  def install
    bin.install "narc"
  end

  test do
    assert_match version, shell_output("#{bin}/narc version")
  end
end
